services:
  db:
    container_name: database
    image: mongo:latest
    ports:
      - 27017:27017
  
  app:
    build: .
    container_name: application
    image: todo-service:latest
    ports:
      - 3000:3000
