services:
  todo-database:
    container_name: todo-database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  
  todo-application:
    build: .
    container_name: todo-application
    env_file:
      - .env
    image: todo-service:latest
    ports:
      - 3000:3000
